# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
# source 'https://github.com/CocoaPods/Specs.git'
# platform :ios, '11.0'

target 'NaverMovieList' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
pod 'Nuke', '~> 9.0'
pod 'Alamofire', '~> 5.2'
  # Pods for NaverMovieList

end
